### ISSUE TITLE
Add documents

### ISSUE THREAD

**Issue by slamer59** [lrvinye/meilisearch-ui#2]
Is there a way to easily add documents in the UI ?

**Comment by lrvinye** [comment]
Hi @slamer59  
You mean to add documents in batches ? or import a huge set of documents ?
If you wanna to add documents just dozens, 
there is a tip that `copy your document(s) (json array or object) before click "Add Documents" button`, 
and then you can see the json in clipboard has been pasted in editor automaticity.

For hundreds of documents import, i recommand to use official api to do it.

Maybe I would complete this feature to import a json file by one click in the future,
or anyone could submit a PR for that, i would be pleasured 💪

**Comment by slamer59** [comment]
Maybe I didnt see this UI.
I will check.
Yes it is just for small test.

Le sam. 22 oct. 2022, 14:34, Kyrie Lrvinye ***@***.***> a
écrit :

**Comment by slamer59** [comment]
Hi, thanks for the update I will have a look in few days. 

Something I miss is that my postgres database doesnot share the same schema as meilisearch.
Do you think I can change it with dbt before loading to meilisearch ? Just curious ?

**Comment by riccox** [comment]
> Hi, thanks for the update I will have a look in few days.
> 
> Something I miss is that my postgres database doesnot share the same schema as meilisearch. Do you think I can change it with dbt before loading to meilisearch ? Just curious ?

I think you should write a  migration script to convert these data for matching your schema in meilisearch, then import them to meilisearch.
